# Generated by Django 5.1.3 on 2024-11-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_user_address'),
        ('Ruqyah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruqyah_assessments_appointment', to='Main.appointment'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruqyah_assessments_user', to='Main.user'),
        ),
    ]
