# Generated by Django 5.1.3 on 2024-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
