# Generated by Django 5.1.3 on 2024-11-27 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hijama', '0002_assessment_appointment'),
        ('Main', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijama_assessments', to='Main.appointment'),
        ),
    ]
